
### Show All Categories
GET http://localhost:3000/api/v1/category
Content-Type: application/json

### Show All News
GET http://localhost:3000/api/v1/news?limit=2&page=2
Content-Type: application/json